service: urlscrape
frameworkVersion: '>=1.1.0 <3.0.0'
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2

functions:
  scraper:
    handler: handler.scrapper
    description: scrape metadata from a given webpage url.
    events:
      - http:
          path: scrape
          method: post
